# Site settings
title: KEVLAB.COM
description: "A site providing updates of research being carried out in the laboratory of Dr Kevin Dudley."
baseurl: "" 
url: "http://kevlab.com" 
tagline: "Exploring The Gap Between The Genome And The Phenome"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
